services:
  websocket:
    build: .
    image: solipsisai/websocket:latest
    command: python -m lagos serve -H 0.0.0.0 -P 8001
    ports:
      - "8001:8001"
    networks:
      - ws-net

  chatbot:
    image: solipsisai/websocket:latest
    depends_on:
      - websocket
    command: python -m lagos start -m "models/output-small" -c "ws://websocket:8001"
    volumes:
      - ${MODELS_DIR}:/app/models
    networks:
      - ws-net

networks:
  ws-net: {}
